M48
; DRILL file {KiCad 9.0.4} date 2025-08-26T13:13:36-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-26T13:13:36-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X149.1Y-93.8
X151.36Y-89.483
T2
X145.7Y-89.16
X145.7Y-91.7
X156.0Y-89.06
X156.0Y-91.6
M30
